In [0]:
import numpy as np
A = np.matrix([
    [0, 1, 0, 0],
    [0, 0, 1, 1], 
    [0, 1, 0, 0],
    [1, 0, 1, 0]],
    dtype=float
)

In [3]:
X = np.matrix([
            [i, -i]
            for i in range(A.shape[0])
        ], dtype=float)
X

matrix([[ 0.,  0.],
        [ 1., -1.],
        [ 2., -2.],
        [ 3., -3.]])

In [4]:
#Propogation Rule
A * X

matrix([[ 1., -1.],
        [ 5., -5.],
        [ 1., -1.],
        [ 2., -2.]])

In [5]:
#Adding self loops
I = np.matrix(np.eye(A.shape[0]))
I

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [6]:
A_hat = A + I
A_hat * X

matrix([[ 1., -1.],
        [ 6., -6.],
        [ 3., -3.],
        [ 5., -5.]])

In [0]:
D_hat = D + I

In [8]:
D = np.array(np.sum(A, axis=0))[0]
D = np.matrix(np.diag(D))
D

matrix([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 2., 0.],
        [0., 0., 0., 1.]])

In [9]:
D**-1 * A

matrix([[0. , 1. , 0. , 0. ],
        [0. , 0. , 0.5, 0.5],
        [0. , 0.5, 0. , 0. ],
        [1. , 0. , 1. , 0. ]])

In [10]:
D**-1 * A * X

matrix([[ 1. , -1. ],
        [ 2.5, -2.5],
        [ 0.5, -0.5],
        [ 2. , -2. ]])

In [0]:
 W = np.matrix([
             [1, -1],
             [-1, 1]
         ])

In [18]:
mt=D_hat**-1 * A_hat * X * W
mt

matrix([[ 1., -1.],
        [ 4., -4.],
        [ 2., -2.],
        [ 5., -5.]])

In [0]:
def ReLU(x):
    return x * (x > 0)

In [32]:
mt=[[ 1., -1.],
        [ 4., -4.],
        [ 2., -2.],
        [ 5., -5.]]
mt

[[1.0, -1.0], [4.0, -4.0], [2.0, -2.0], [5.0, -5.0]]

In [33]:
for i in range(4):
  for j in range(2):
    mt[i][j]=ReLU(mt[i][j])
mt

[[1.0, -0.0], [4.0, -0.0], [2.0, -0.0], [5.0, -0.0]]

In [0]:
#Building GCN
from networkx import karate_club_graph, to_numpy_matrix
zkc = karate_club_graph()
order = sorted(list(zkc.nodes()))
A = to_numpy_matrix(zkc, nodelist=order)
I = np.eye(zkc.number_of_nodes())
A_hat = A + I
D_hat = np.array(np.sum(A_hat, axis=0))[0]
D_hat = np.matrix(np.diag(D_hat))

In [0]:
W_1 = np.random.normal(
    loc=0, scale=1, size=(zkc.number_of_nodes(), 4))
W_2 = np.random.normal(
    loc=0, size=(W_1.shape[1], 2))

In [0]:
def gcn_layer(A_hat, D_hat, X, W):
  x=D_hat**-1 * A_hat * X * W
  return np.maximum(x, 0, x)
H_1 = gcn_layer(A_hat, D_hat, I, W_1)
H_2 = gcn_layer(A_hat, D_hat, H_1, W_2)
output = H_2

In [39]:
feature_representations = {
    node: np.array(output)[node] 
    for node in zkc.nodes()}
feature_representations

{0: array([0., 0.]),
 1: array([0., 0.]),
 2: array([0.        , 0.21904491]),
 3: array([0.18792531, 0.        ]),
 4: array([0.22327006, 0.        ]),
 5: array([0.09671562, 0.        ]),
 6: array([0.12334957, 0.        ]),
 7: array([0.26205203, 0.        ]),
 8: array([0.        , 0.11069593]),
 9: array([0.        , 0.49272904]),
 10: array([0.14629539, 0.        ]),
 11: array([0.22980836, 0.        ]),
 12: array([0.17075053, 0.        ]),
 13: array([0.1764936, 0.       ]),
 14: array([0.       , 0.4037232]),
 15: array([0.        , 0.13431332]),
 16: array([0., 0.]),
 17: array([0.18660424, 0.        ]),
 18: array([0.        , 0.12668171]),
 19: array([0.16076076, 0.        ]),
 20: array([0.        , 0.03097627]),
 21: array([0., 0.]),
 22: array([0.        , 0.29982818]),
 23: array([0.        , 0.11846057]),
 24: array([0.07260365, 0.        ]),
 25: array([0.08402117, 0.        ]),
 26: array([0.        , 0.32890654]),
 27: array([0.02940303, 0.        ]),
 28: array([0.